from __future__ import annotations

PIPELINE_VERSION = "fusion-2026-04-27"
STORE_SCHEMA_VERSION = "store-v2"
SCORE_SCHEMA_VERSION = "score-v5"

MISSING_PLACEHOLDERS = {"", "nan", "null", "none", "n/a"}
BLANK_SENSITIVE_COLUMNS = ["author_hash", "original_text", "english_keywords", "primary_theme"]
COMMON_MULTI_PART_SUFFIXES = {
    "co.uk",
    "org.uk",
    "gov.uk",
    "ac.uk",
    "com.au",
    "net.au",
    "org.au",
    "co.jp",
    "com.br",
    "com.tr",
    "com.mx",
    "co.in",
    "com.cn",
}

REQUIRED_BATCH_TABLES = ("cleaned_messages", "text_clusters", "text_window_clusters")
REQUIRED_CLEANED_MESSAGE_COLUMNS = (
    "message_id",
    "original_text",
    "normalized_text",
    "text_hash",
    "keyword_count",
    "time_window_bucket",
    "author_hash",
    "author_type",
    "text_length_chars",
    "token_count",
    "unique_token_count",
    "max_token_frequency",
    "max_token_ratio",
    "repeated_token_count_over_2",
    "hashtag_count",
    "hashtag_density_chars",
    "hashtag_density_tokens",
    "roberta_score",
    "semantic_model_applied_flag",
    "is_long_text_flag",
)
REQUIRED_AUTHOR_SCORE_COLUMNS = (
    "author_hash",
    "author_score",
    "author_hard_hourly_flag",
    "max_posts_one_hour",
    "language_nunique",
    "theme_nunique",
    "sentiment_std",
    "median_interpost_sec",
)
REQUIRED_SCORED_MESSAGE_COLUMNS = (
    "message_id",
    "author_hash",
    "author_type",
    "same_text_repeat_count",
    "same_text_unique_author_count",
    "same_text_time_window_count",
    "hashtag_count",
    "max_token_frequency",
    "max_token_ratio",
    "spam_pattern_flag",
    "hard_bot_cluster_flag",
    "hard_same_text_repeat_flag",
    "author_hard_hourly_flag",
    "author_score",
    "message_score",
    "behavioral_score",
    "roberta_score",
    "behavioral_confidence_weight",
    "roberta_confidence_weight",
    "behavioral_effective_weight",
    "roberta_effective_weight",
    "final_score_before_rules",
    "final_score",
)

CLEANED_MESSAGE_SCHEMA = {
    "row_fingerprint": "TEXT NOT NULL UNIQUE",
    "original_text": "TEXT",
    "normalized_text": "TEXT",
    "text_hash": "TEXT",
    "english_keywords_clean": "TEXT",
    "keyword_count": "INTEGER",
    "primary_theme": "TEXT",
    "sentiment": "REAL",
    "main_emotion": "TEXT",
    "language": "TEXT",
    "url": "TEXT",
    "raw_url_domain": "TEXT",
    "registered_domain": "TEXT",
    "subdomain": "TEXT",
    "date": "TEXT",
    "time_window_bucket": "INTEGER",
    "author_hash": "TEXT",
    "author_type": "TEXT",
    "author_hash_missing_flag": "INTEGER",
    "text_length_chars": "INTEGER",
    "token_count": "INTEGER",
    "unique_token_count": "INTEGER",
    "max_token_frequency": "INTEGER",
    "max_token_ratio": "REAL",
    "repeated_token_count_over_2": "INTEGER",
    "hashtag_count": "INTEGER",
    "hashtag_density_chars": "REAL",
    "hashtag_density_tokens": "REAL",
    "roberta_score": "REAL",
    "semantic_model_applied_flag": "INTEGER",
    "is_short_text": "INTEGER",
    "is_long_text_flag": "INTEGER",
    "is_empty_text": "INTEGER",
}

LEAN_STORE_COLUMNS = (
    "row_fingerprint",
    "original_text",
    "normalized_text",
    "text_hash",
    "keyword_count",
    "primary_theme",
    "sentiment",
    "language",
    "registered_domain",
    "date",
    "time_window_bucket",
    "author_hash",
    "author_type",
    "author_hash_missing_flag",
    "text_length_chars",
    "token_count",
    "unique_token_count",
    "max_token_frequency",
    "max_token_ratio",
    "repeated_token_count_over_2",
    "hashtag_count",
    "hashtag_density_chars",
    "hashtag_density_tokens",
    "roberta_score",
    "semantic_model_applied_flag",
    "is_short_text",
    "is_long_text_flag",
    "is_empty_text",
)

DEBUG_EXTRA_STORE_COLUMNS = (
    "original_text",
    "english_keywords_clean",
    "main_emotion",
    "url",
    "raw_url_domain",
    "subdomain",
)
